displayName=Detailed Overlay
author=Aiirik
description=Shows overlays for potions doses, staves runes, and combat styles with max hit
tags=inventory,items,doses,staff,combat,overlay,information,runes,max,hit,maxhit,potion
plugins=com.aiirik.detailedoverlay.DetailedOverlayPlugin
